pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh "docker build -t multibranch-test:${env.BRANCH_NAME} -f MultibranchTest/Dockerfile ."
            }
        }
    }
}
